import type { Metadata } from "next";
import { Cairo, Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar";

const cairo = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Next Demo 4 Master Class",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={cairo.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
