import type { Metadata } from "next";
import { Cairo, Inter } from "next/font/google";
import "./globals.css";

export const dynamic = 'force-dynamic'

const cairo = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Next Demo 4 Master Class",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning={true}>
      <body className={cairo.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
